{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.oiti",
    "module": "oiti-network",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "oiti-network-1.0.0.aar",
          "url": "oiti-network-1.0.0.aar",
          "size": 43139,
          "sha512": "d84bf86ff1c705da4f8123e98fda1eda78a894ba29735de76d23f585acb3244e90f96a2071a120f477d4bd3f359ef2ca3b3e544b03893b497b7875c5b968d9bc",
          "sha256": "ecf030a1144a1d7e93bdc56c495f77b484ac3d371fe9d35d9d43f69bcbd8dd8a",
          "sha1": "66514ea090c62fca4f8b7a22f47da14e14d88c29",
          "md5": "977bf7e5d100fcd0355e87bdb932664f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "core",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "oiti-network-1.0.0.aar",
          "url": "oiti-network-1.0.0.aar",
          "size": 43139,
          "sha512": "d84bf86ff1c705da4f8123e98fda1eda78a894ba29735de76d23f585acb3244e90f96a2071a120f477d4bd3f359ef2ca3b3e544b03893b497b7875c5b968d9bc",
          "sha256": "ecf030a1144a1d7e93bdc56c495f77b484ac3d371fe9d35d9d43f69bcbd8dd8a",
          "sha1": "66514ea090c62fca4f8b7a22f47da14e14d88c29",
          "md5": "977bf7e5d100fcd0355e87bdb932664f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "oiti-network-1.0.0-sources.jar",
          "url": "oiti-network-1.0.0-sources.jar",
          "size": 14122,
          "sha512": "fb5b12c68f1516138695dfbe3ff0887e41201acb193d32b4617ef3813c82da3b0d81e636a644a07c9bd0d9e86d10787e5927c27701ba98d9e3d6d21020069ad7",
          "sha256": "dc9f5a40742c83eef50320bb04f6f50ffecd45cd0b2864457d6e90ab5db947c3",
          "sha1": "e4701447aab81722a398260d5150e8a53c4b602f",
          "md5": "502db0fb69195cfffd460750ad5c1ea6"
        }
      ]
    }
  ]
}
