{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.oiti",
    "module": "di",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "di-1.0.0.aar",
          "url": "di-1.0.0.aar",
          "size": 1750,
          "sha512": "d7315654622449744e7c08bd0f8cc51f9dca87a1f7a5bdce18d2f098206974b732e38b432c04a3dbeecfb57fe9129f8879d6e85af5413fd2474413aeb11d2a06",
          "sha256": "6d97185d42876eafda80fcb8b01b2093a3c0289d24beec1307c6928ed91de21d",
          "sha1": "b0e3e8223fd4072d5aef003cd6cd747be848262f",
          "md5": "6842b8771775a3f61e9239bca9a970d8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "di-1.0.0.aar",
          "url": "di-1.0.0.aar",
          "size": 1750,
          "sha512": "d7315654622449744e7c08bd0f8cc51f9dca87a1f7a5bdce18d2f098206974b732e38b432c04a3dbeecfb57fe9129f8879d6e85af5413fd2474413aeb11d2a06",
          "sha256": "6d97185d42876eafda80fcb8b01b2093a3c0289d24beec1307c6928ed91de21d",
          "sha1": "b0e3e8223fd4072d5aef003cd6cd747be848262f",
          "md5": "6842b8771775a3f61e9239bca9a970d8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "di-1.0.0-sources.jar",
          "url": "di-1.0.0-sources.jar",
          "size": 895,
          "sha512": "8d8c05f0e6126fbf0d33f9976d218f69d045572fe2dafff3f9401a581c5aba180a262a51a3969cd1cc115a5dbc1f80801d44676049b0cfc9d94569af97e9edc4",
          "sha256": "d4e264a49440c4bbfca930ca494829465ebdefcc473665f3ce816e19bf997627",
          "sha1": "2193cf3d344066b22ebfc38855dbc897cfd7dd91",
          "md5": "b83194de52f13ccf21f9febbd199788c"
        }
      ]
    }
  ]
}
