{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.oiti",
    "module": "data",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "data-1.0.0.aar",
          "url": "data-1.0.0.aar",
          "size": 198219,
          "sha512": "5b5ca68f35fb4e3038dfeeb3ad0b23339e5e3a5d8c39ff2c8c31e94e511cc052be92c0f8e9b9a6cb6901db657eed1fc31dc33246ed1be8753808e330c48a3725",
          "sha256": "f5670b75c25b229c2817b64f74821271ded10354f2df52045368242f34776f06",
          "sha1": "3f1fcf523c7e073c261dcfa2ae8141155a447850",
          "md5": "e8e91d8573c066a3d44280d64fbd373b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "domain",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "remote",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "oiti-network",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "utils",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "data-1.0.0.aar",
          "url": "data-1.0.0.aar",
          "size": 198219,
          "sha512": "5b5ca68f35fb4e3038dfeeb3ad0b23339e5e3a5d8c39ff2c8c31e94e511cc052be92c0f8e9b9a6cb6901db657eed1fc31dc33246ed1be8753808e330c48a3725",
          "sha256": "f5670b75c25b229c2817b64f74821271ded10354f2df52045368242f34776f06",
          "sha1": "3f1fcf523c7e073c261dcfa2ae8141155a447850",
          "md5": "e8e91d8573c066a3d44280d64fbd373b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "data-1.0.0-sources.jar",
          "url": "data-1.0.0-sources.jar",
          "size": 19357,
          "sha512": "aaae220d0bca9566f42fff5560425c79795e7b3e68fe51db1eaa722bff94b8acef7944985e982b2a2c82cace08212a0f56300b115c81299f4eedb647ac60c735",
          "sha256": "91ed804482291e07987a7e9c6b1707f53c35b4bcc35e0ea29c13a9fe1e12d79b",
          "sha1": "8fd9a7973ce442765420272892b1719e3a7fef6f",
          "md5": "760bc9eb1cacc8a718ede3e45e366559"
        }
      ]
    }
  ]
}
